name: test

on: push

jobs:
  contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm test
